[package]
name = "udp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "net", "sync", "macros"] }
traffic-server-core = { path = "../traffic-server-core" }